### ISSUE TITLE
I fail to run from sbt => no main class or java.lang.ClassNotFoundException: SimpleServer

### ISSUE THREAD

**Issue by petervandenabeele** [wandoulabs/spray-websocket#74]
Hi,

I can run the example SimpleServer perfectly from IntelliJ.

However, trying `sbt run` =>
```
> compile
[info] Formatting 1 Scala source {file:/Users/peter_v/Documents/data/.../spray-websocket-wandou-peter_v/}spray-websocket-examples-simple(compile) ...
[info] Compiling 3 Scala sources to /Users/peter_v/Documents/data/.../spray-websocket-wandou-peter_v/examples/spray-websocket-simple/target/scala-2.11/classes...
[success] Total time: 3 s, completed Apr 26, 2015 8:17:44 PM
> run
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
```

or in `sbt` =>
```
> runMain SimpleServer
[info] Running SimpleServer 
[error] (run-main-0) java.lang.ClassNotFoundException: SimpleServer
java.lang.ClassNotFoundException: SimpleServer
```

Should I change something? Once I understand what I need to change, I will try to submit a patch in code or documentation to make this easier for newcomers.

I now tried one more time with a fresh `git clone` of the newest version, and same result:
```
➜  spray-websocket git:(master) git log -1 | head -1 # latest sha
commit e10482e26638168965bcb4bbec95e82b0609a431
➜  spray-websocket git:(master) sbt run
[info] Loading project definition from /Users/peter_v/Documents/data/.../new-websocket-wandou/spray-websocket/project
[info] Updating {file:/Users/peter_v/Documents/data/.../new-websocket-wandou/spray-websocket/project/}spray-websocket-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/peter_v/Documents/data/.../new-websocket-wandou/spray-websocket/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to spray-websocket-root (in build file:/Users/peter_v/Documents/data/.../new-websocket-wandou/spray-websocket/)
[info] Updating {file:/Users/peter_v/Documents/data/.../new-websocket-wandou/spray-websocket/}spray-websocket-root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last spray-websocket-root/compile:run for the full output.
[error] (spray-websocket-root/compile:run) No main class detected.
[error] Total time: 1 s, completed Apr 27, 2015 8:48:21 AM
```
Thanks !

**Comment by petervandenabeele** [comment]
Still fighting with this ... I can see there are several subprojects, but failing to run anything in the spray-websocket-examples subproject (after reading most of the `sbt` tutorial ...). Any help would be appreciated. Thanks :-)

```
> show version
[info] spray-websocket-examples-simple/*:version
[info] 	0.1.5-SNAPSHOT
[info] spray-websocket-examples/*:version
[info] 	0.1.5-SNAPSHOT
[info] spray-websocket/*:version
[info] 	0.1.5-SNAPSHOT
[info] spray-websocket-root/*:version
[info] 	0.1.5-SNAPSHOT
```

**Comment by petervandenabeele** [comment]
Finally found it ... I will contribute a documentation patch to make it easier for newcomers to run the examples from `sbt` (sbt documentation explain if full glory how to set variables etc. but not easy to find how to actually run a sub project ...). This is it:

```
> projects
[info] In file:/Users/peter_v/Documents/data/.../new-websocket-wandou/spray-websocket/
[info] 	   spray-websocket
[info] 	 * spray-websocket-examples
[info] 	   spray-websocket-examples-simple
[info] 	   spray-websocket-root
> project spray-websocket-examples-simple
[info] Set current project to spray-websocket-examples-simple (in build file:/Users/peter_v/Documents/data/.../new-websocket-wandou/spray-websocket/)
> compile
[success] Total time: 0 s, completed Apr 27, 2015 10:00:21 PM
> run

Multiple main classes detected, select one to run:

 [1] spray.can.websocket.examples.SimpleClient
 [2] spray.can.websocket.examples.SimpleServer

Enter number: 2

[info] Running spray.can.websocket.examples.SimpleServer 
Hit ENTER to exit ...
```

**Comment by petervandenabeele** [comment]
OK, sorry for the noise. This _was_ documented in the README:

"... Build and run the project: sbt 'project spray-websocket-examples-simple' run ..."
